Icon guidance
nhsuk/nhsapp-frontend pull request #104
Opened 2024-07-10 09:39 UTC by davidhunter08

2024-07-19 16:56 UTC, davidhunter08 commented
Messages with unread status icons need updating as they don't currently have the red dot on them.

<img width="296" alt="Screenshot 2024-07-19 at 17 52 26" src="https://github.com/user-attachments/assets/b0e97c39-4001-48fe-a708-916b2aaaa410">

https://www.figma.com/design/6f2CbcZ7cnpNrtKEcfQp8X/NHS-App-Design-System?node-id=1295-1786&t=XJrYxovldYo5IbsQ-1

<img width="202" alt="Screenshot 2024-07-19 at 17 55 48" src="https://github.com/user-attachments/assets/0df33498-fa19-4b79-8364-7dfbaaa02a11">

2024-07-22 11:01 UTC, edwardscull requested changes

2024-07-22 11:01 UTC, edwardscull commented on src/all.scss
> +@import "styles/icon/icons";
you can rename this file to `_index.scss` and then you won't need to do `icon/icons`. https://sass-lang.com/documentation/at-rules/use/#index-files

2024-07-22 11:01 UTC, edwardscull commented on src/styles/icon/_icons.scss
> +.nhsapp-icon {
```sass
.nhsapp-icon {
 // styles
 &__unread-indicator {
  // styles
 }
}
```
The `&` can make this a little cleaner meaning it's easier to add/extend in the future.

2024-07-22 11:20 UTC, davidhunter08 commented on src/all.scss
> +@import "styles/icon/icons";
I was following what we already had for the other components / styles. 

For example: https://github.com/nhsuk/nhsapp-frontend/blob/main/src/components/badge/_badge.scss

Do you recommend changing them all to `_index.scss`?

2024-07-22 11:25 UTC, edwardscull commented on src/all.scss
> +@import "styles/icon/icons";
I think it's a good thing to make consistent yeh, but happy for it not be changed in this PR

2024-07-22 12:18 UTC, merged