Docs restructuring
nhsuk/nhsapp-frontend pull request #7
Opened 2024-04-17 16:08 UTC by mikemonteith

- Render nunjucks tags inside markdown files
- Simplify file structure
- Use markdown for content pages
- Add a 'plain' layout with title and content
- Recompile docs when our source changes (useful during development of own component nunjucks macros)

2024-04-17 18:02 UTC, davidhunter08 requested changes
Looks good. Just need the heading class name changing.

2024-04-17 18:02 UTC, davidhunter08 commented on docs/_includes/layouts/plain.njk
> +  <h1 class="govuk-heading-xl">
Should be `nhsuk-heading-xl`

2024-04-18 08:39 UTC, mikemonteith commented on docs/_includes/layouts/plain.njk
> +  <h1 class="govuk-heading-xl">
I've removed the class completely

2024-04-18 08:41 UTC, davidhunter08 approved these changes
LGTM

2024-04-18 08:41 UTC, merged